version: '3.9'
services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - wordpress
    volumes:
      - wordpress_files:/var/www/html
  mariadb:
    build: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_DATABASE=wordpress
    volumes:
      - mysql_data:/var/lib/mysql
  wordpress:
    build: wordpress
    container_name: wordpress
    environment:
      - DB_HOST=mariadb:3306
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=wordpress
    depends_on: 
      - mariadb
    volumes:
      - wordpress_files:/var/www/html
volumes:
  wordpress_files:
  mysql_data:
