version: '3.9'
services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - 8080:80
  wordpress:
    build: wordpress
    container_name: wordpress
    environment:
      - DB_HOST=mariadb:3306
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=wordpress
  mariadb:
    build: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_DATABASE=wordpress
