FROM debian:buster

RUN apt-get update && apt-get -y install nginx


# RUN touch /etc/apt/sources.list.d/nginx.list
# RUN echo "deb http://nginx.org/packages/ubuntu/ precise nginx" >> /etc/apt/sources.list.d/nginx.list
# RUN echo "deb-src http://nginx.org/packages/ubuntu/ precise nginx" >> /etc/apt/sources.list.d/nginx.list
# RUN curl http://nginx.org/keys/nginx_signing.key | apt-key add -
# RUN apt-get update
# RUN apt-get install -y nginx
